package handlers

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"

	"github.com/labstack/echo/v4"
)

type AIRequest struct {
	Text string `json:"text"`
}

type AIResponse struct {
	CorrectedText    string `json:"corrected_text"`
	LearningFeedback string `json:"learning_feedback"`
}

type AIHandler struct{}

func (h *AIHandler) Correct(c echo.Context) error {
	var req AIRequest
	if err := c.Bind(&req); err != nil {
		log.Printf("Request binding error: %v", err)
		return c.JSON(http.StatusBadRequest, map[string]string{"error": "invalid request"})
	}

	log.Printf("Received text: %s", req.Text)

	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		log.Println("GEMINI_API_KEY not set")
		return c.JSON(http.StatusInternalServerError, map[string]string{"error": "API key not set"})
	}

	log.Printf("API Key exists (length: %d)", len(apiKey))

	// Gemini API呼び出し
	url := "https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent?key=" + apiKey


	prompt := fmt.Sprintf("Please correct this English sentence and provide feedback: %s", req.Text)

	payload := map[string]interface{}{
		"contents": []map[string]interface{}{
			{
				"parts": []map[string]string{
					{
						"text": prompt,
					},
				},
			},
		},
	}

	jsonPayload, err := json.Marshal(payload)
	if err != nil {
		log.Printf("JSON marshal error: %v", err)
		return c.JSON(http.StatusInternalServerError, map[string]string{"error": "failed to create request"})
	}

	log.Printf("Calling Gemini API with URL: %s", url[:50]+"...")

	resp, err := http.Post(url, "application/json", bytes.NewBuffer(jsonPayload))
	if err != nil {
		log.Printf("HTTP request error: %v", err)
		return c.JSON(http.StatusInternalServerError, map[string]string{"error": "failed to call Gemini API"})
	}
	defer resp.Body.Close()

	log.Printf("Gemini API response status: %d", resp.StatusCode)

	// レスポンスボディを読み取って詳細なエラー情報を取得
	var responseBody bytes.Buffer
	responseBody.ReadFrom(resp.Body)
	responseBodyStr := responseBody.String()

	log.Printf("Gemini API response body: %s", responseBodyStr)

	if resp.StatusCode != http.StatusOK {
		return c.JSON(http.StatusInternalServerError, map[string]string{
			"error":    "Gemini API error",
			"status":   fmt.Sprintf("%d", resp.StatusCode),
			"response": responseBodyStr,
		})
	}

	var result map[string]interface{}
	if err := json.Unmarshal(responseBody.Bytes(), &result); err != nil {
		log.Printf("JSON decode error: %v", err)
		return c.JSON(http.StatusInternalServerError, map[string]string{"error": "failed to parse Gemini response"})
	}

	log.Printf("Parsed result: %+v", result)

	// Geminiの返答を整形
	text := ""
	if candidates, ok := result["candidates"].([]interface{}); ok && len(candidates) > 0 {
		if candidate, ok := candidates[0].(map[string]interface{}); ok {
			if content, ok := candidate["content"].(map[string]interface{}); ok {
				if parts, ok := content["parts"].([]interface{}); ok && len(parts) > 0 {
					if part, ok := parts[0].(map[string]interface{}); ok {
						if textValue, ok := part["text"].(string); ok {
							text = textValue
						}
					}
				}
			}
		}
	}

	if text == "" {
		log.Println("No text found in Gemini response")
		return c.JSON(http.StatusInternalServerError, map[string]string{"error": "no response from AI"})
	}

	log.Printf("Extracted text: %s", text)

	return c.JSON(http.StatusOK, AIResponse{
		CorrectedText:    text,
		LearningFeedback: "Generated by Gemini",
	})
}