package handlers

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"

	"github.com/labstack/echo/v4"
)

type AIRequest struct {
	Text string `json:"text"`
}

type AIResponse struct {
	CorrectedText    string `json:"corrected_text"`
	LearningFeedback string `json:"learning_feedback"`
}

type AIHandler struct{}

func (h *AIHandler) Correct(c echo.Context) error {
	var req AIRequest
	if err := c.Bind(&req); err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{"error": "invalid request"})
	}

	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		return c.JSON(http.StatusInternalServerError, map[string]string{"error": "API key not set"})
	}

	// --- Gemini API 呼び出し ---
	url := "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=" + apiKey

	payload := map[string]interface{}{
		"contents": []map[string]interface{}{
			{
				"parts": []map[string]string{
					{
						"text": fmt.Sprintf("Please correct this English sentence and give feedback: %s", req.Text),
					},
				},
			},
		},
	}

	jsonPayload, _ := json.Marshal(payload)

	resp, err := http.Post(url, "application/json", bytes.NewBuffer(jsonPayload))
	if err != nil {
		return c.JSON(http.StatusInternalServerError, map[string]string{"error": "failed to call Gemini API"})
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return c.JSON(http.StatusInternalServerError, map[string]string{"error": "Gemini API error"})
	}

	var result map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return c.JSON(http.StatusInternalServerError, map[string]string{"error": "failed to parse Gemini response"})
	}

	// Gemini の返答を整形
	text := ""
	if candidates, ok := result["candidates"].([]interface{}); ok && len(candidates) > 0 {
		c := candidates[0].(map[string]interface{})
		if content, ok := c["content"].(map[string]interface{}); ok {
			if parts, ok := content["parts"].([]interface{}); ok && len(parts) > 0 {
				part := parts[0].(map[string]interface{})
				text = part["text"].(string)
			}
		}
	}

	// とりあえず Gemini の返答を corrected_text にまとめる
	return c.JSON(http.StatusOK, AIResponse{
		CorrectedText:    text,
		LearningFeedback: "Generated by Gemini",
	})
}
